/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdktools>

public Plugin:myinfo = 
{
	name = "Event Tester",
	author = "MI 5",
	description = "This plugin is used to test L4D events",
	version = "1.0",
	url = "<- URL ->"
}

public OnPluginStart()
{
	HookEvent("bot_player_replace", Event_EventToBeTested)
}

public Action:Event_EventToBeTested(Handle:event, const String:name[], bool:dontBroadcast)
{
	PrintToChatAll ("Player Replaced Bot");
	
	new client = GetClientOfUserId(GetEventInt(event, "player"));
	
	SetEntityHealth(client, 50);
}


////////////////////////////