/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdktools>
#pragma semicolon 1
#define PLUGIN_VERSION "1.0"
#define DEBUG 0
#define TEAM_INFECTED 3

public Plugin:myinfo = 
{
	name = "L4D2 ChangeTeam Test",
	author = "MI 5",
	description = "Changes the player's team",
	version = PLUGIN_VERSION,
	url = "<- URL ->"
}

new offsetTeamNum; // This sets the team for the player

public OnPluginStart()
{
	offsetTeamNum = FindSendPropInfo("CTerrorPlayer", "m_iTeamNum");
	RegConsoleCmd("sm_ji", JoinInfected);
	RegConsoleCmd("sm_js", JoinSurvivors);
	RegConsoleCmd("sm_sp", JoinSpectator);
	RegConsoleCmd("sm_team", Teamer);
}

public Action:JoinInfected(client, args)
{
	if (client)
	{
		ChangeClientTeam(client, TEAM_INFECTED);
	}
}

public Action:JoinSurvivors(client, args)
{
	if (client)
	{
		FakeClientCommand(client, "jointeam 2");
	}
}

// Joining spectators is for developers only, commented in the final

public Action:JoinSpectator(client, args)
{
	if (client)
	{
		ChangeClientTeam(client, 1);
	}
}

public Action:Teamer(client, args)
{
	if (client)
	{
		decl String:value[64];
		GetCmdArg(1, value, 64);
		PrintToChatAll("TeamNum = %i", offsetTeamNum);
		SetEntData(client, offsetTeamNum, StringToInt(value));
	}
}