/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "Spectator Plugin",
	author = "MI 5",
	description = "Joins Spectator",
	version = "1.0",
	url = "<- URL ->"
}

public OnPluginStart()
{
	RegConsoleCmd("sm_sp", JoinSpectator);
}

public Action:JoinSpectator(client, args)
{
	if (client)
	{
		ChangeClientTeam(client, 1);
	}
}