/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "[L4D] Team DeathMatch",
	author = "MI 5",
	description = "Allows survivors to respawn and keeps track of score",
	version = "1.0",
	url = "none"
}

public OnPluginStart()
{
	//Hook the event for a player's death
	HookEvent("player_death", PlayerDeath, EventHookMode_Pre);
	
	
}
